# =========================
# SCAN-X PATCH V4 (one-go) - FIX pdf_report_service.dart corruption + restore build/tests
# Run from your project root:
#   cd C:\Users\Acer\scanx\scan-x
#   powershell -ExecutionPolicy Bypass -File .\APPLY_SCANX_PATCH_V4.ps1
# =========================

$ErrorActionPreference = "Stop"

function Timestamp() { Get-Date -Format "yyyyMMdd_HHmmss" }
function Backup-File([string]$path) {
  if (Test-Path -LiteralPath $path) {
    $bak = "$path.bak_$(Timestamp)"
    Copy-Item -LiteralPath $path -Destination $bak -Force
    Write-Host "Backup: $bak" -ForegroundColor DarkGray
  }
}

# Resolve project root as current directory
$ProjectRoot = (Resolve-Path -LiteralPath ".").Path
Write-Host "=== APPLY SCAN-X PATCH V4: Repair pdf_report_service.dart (compile-safe) + restore report sections ==="
Write-Host "ProjectRoot: $ProjectRoot"

$pdfPath = Join-Path $ProjectRoot "lib\core\services\pdf_report_service.dart"

# If a recent backup exists and current file is clearly corrupted, restore backup first (safety net)
$bakCandidates = Get-ChildItem -LiteralPath (Split-Path $pdfPath -Parent) -Filter "pdf_report_service.dart.bak_*" -ErrorAction SilentlyContinue | Sort-Object Name -Descending
if ($bakCandidates -and (Test-Path -LiteralPath $pdfPath)) {
  $cur = Get-Content -LiteralPath $pdfPath -Raw -ErrorAction SilentlyContinue
  if ($cur -match "import\s+''dart" -or $cur -match "import\s+''package" -or $cur -match "String starting with ' must end with '") {
    $latestBak = $bakCandidates[0].FullName
    Write-Host "Restoring from latest backup: $latestBak" -ForegroundColor Yellow
    Copy-Item -LiteralPath $latestBak -Destination $pdfPath -Force
  }
}

Backup-File $pdfPath

# Write a known-good implementation (no fancy escaping; single quotes only where needed)
$fixed = @'
import 'dart:typed_data';

import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

import 'package:scanx_app/core/utils/text_sanitizer.dart';

class PdfReportService {
  String _s(dynamic v) => sanitizeUiText((v ?? '').toString());

  /// Build short "AI-style" insights from findings (heuristic, no external calls).
  List<String> _aiInsightsFromFindings(List<Map> findings) {
    int hi = 0;
    int med = 0;

    final ports = <String>{};
    final services = <String>{};

    for (final f in findings) {
      final sev = (f['severity'] ?? '').toString().toLowerCase();
      if (sev == 'high' || sev == 'critical') hi++;
      if (sev == 'medium') med++;

      final title = (f['title'] ?? '').toString();
      final details = (f['details'] ?? '').toString();
      final blob = '$title $details';

      final portMatch = RegExp(r'\bport\s+(\d{1,5})\b', caseSensitive: false).firstMatch(blob);
      if (portMatch != null) ports.add(portMatch.group(1)!);

      final svcMatch = RegExp(r'\b(ssh|rdp|telnet|ftp|http|https|smb|snmp)\b', caseSensitive: false).firstMatch(blob);
      if (svcMatch != null) services.add(svcMatch.group(1)!.toUpperCase());
    }

    final out = <String>[];
    out.add('Risk summary: $hi high/critical and $med medium findings were detected.');
    if (ports.isNotEmpty) {
      final p = ports.toList()
        ..sort((a, b) => int.tryParse(a)?.compareTo(int.tryParse(b) ?? 0) ?? a.compareTo(b));
      out.add('Prioritize hardening/closing exposed ports: $p.');
    }
    if (services.isNotEmpty) {
      final s = services.toList()..sort();
      out.add('Review these services for necessity and secure configuration: $s.');
    }
    out.add('Action: patch/update device firmware and OS versions for any devices flagged as outdated.');
    out.add('Action: enforce strong passwords and disable default credentials on routers, IoT, and admin panels.');
    out.add('Action: enable WPA2/WPA3, disable WPS, and isolate IoT devices onto guest/VLAN where possible.');
    return out.map(_s).toList();
  }

  Future<Uint8List> buildReport({required Map<String, dynamic> reportJson}) async {
    final doc = pw.Document();

    final meta = (reportJson['scanMeta'] as Map?)?.cast<String, dynamic>() ?? <String, dynamic>{};
    final findings = (reportJson['findings'] as List?)?.cast<Map>() ?? const <Map>[];
    final score = (reportJson['riskScore'] as Map?)?.cast<String, dynamic>() ?? <String, dynamic>{};

    final insights = _aiInsightsFromFindings(findings);

    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(28),
        build: (context) => [
          pw.Text(
            'SCAN-X Security Report',
            style: pw.TextStyle(fontSize: 22, fontWeight: pw.FontWeight.bold),
          ),
          pw.SizedBox(height: 6),
          pw.Text('Generated by SCAN-X Cyber Labs', style: const pw.TextStyle(fontSize: 10)),
          pw.Divider(),
          pw.Text('Scan Time (UTC): ${_s(meta['scanTimeUtc'] ?? '-')}'),
          pw.Text('Target CIDR: ${_s(meta['targetCidr'] ?? '-')}'),
          pw.Text('Scan Mode: ${_s(meta['scanMode'] ?? '-')}'),
          pw.SizedBox(height: 10),
          pw.Container(
            padding: const pw.EdgeInsets.all(10),
            decoration: pw.BoxDecoration(
              border: pw.Border.all(width: 0.8, color: PdfColors.grey700),
              borderRadius: pw.BorderRadius.circular(6),
            ),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text(
                  'Overall Risk',
                  style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold),
                ),
                pw.SizedBox(height: 4),
                pw.Text('Risk Score: ${_s(score['score'] ?? 0)} (${_s(score['rating'] ?? 'Low')})'),
              ],
            ),
          ),
          pw.SizedBox(height: 12),
          pw.Text('AI Insights', style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold)),
          pw.SizedBox(height: 4),
          pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: insights.map((s) => pw.Bullet(text: s)).toList(),
          ),
          pw.SizedBox(height: 12),
          pw.Text('Findings', style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold)),
          pw.SizedBox(height: 6),
          if (findings.isEmpty)
            pw.Text('No findings were detected.')
          else
            pw.Column(
              children: findings.map((f) {
                final m = f.cast<String, dynamic>();
                return pw.Container(
                  margin: const pw.EdgeInsets.only(bottom: 10),
                  padding: const pw.EdgeInsets.all(10),
                  decoration: pw.BoxDecoration(
                    border: pw.Border.all(width: 0.6, color: PdfColors.grey600),
                    borderRadius: pw.BorderRadius.circular(6),
                  ),
                  child: pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      pw.Text(_s(m['title'] ?? 'Finding'), style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
                      pw.SizedBox(height: 2),
                      pw.Text('Severity: ${_s(m['severity'] ?? '-')}'),
                      pw.Text('Status: ${_s(m['status'] ?? '-')}'),
                      pw.Text('Device: ${_s(m['deviceIp'] ?? '-')}'),
                      if ((m['details'] ?? '').toString().isNotEmpty) pw.Text('Details: ${_s(m['details'])}'),
                      if ((m['evidence'] ?? '').toString().isNotEmpty) pw.Text('Evidence: ${_s(m['evidence'])}'),
                      if ((m['recommendation'] ?? '').toString().isNotEmpty) pw.Text('What to do: ${_s(m['recommendation'])}'),
                    ],
                  ),
                );
              }).toList(),
            ),
          pw.SizedBox(height: 12),
          pw.Text('Disclaimer', style: pw.TextStyle(fontSize: 12, fontWeight: pw.FontWeight.bold)),
          pw.SizedBox(height: 4),
          pw.Text(
            'This report is informational and does not perform exploitation or intrusive actions. '
            'Always obtain authorization before scanning any networks you do not own.',
            style: const pw.TextStyle(fontSize: 9),
          ),
        ],
      ),
    );

    return doc.save();
  }
}
'@

# Ensure target directory exists
$dir = Split-Path $pdfPath -Parent
if (-not (Test-Path -LiteralPath $dir)) { New-Item -ItemType Directory -Path $dir | Out-Null }

Set-Content -LiteralPath $pdfPath -Value $fixed -Encoding UTF8
Write-Host "Wrote: $pdfPath" -ForegroundColor Green

Write-Host ""
Write-Host "=== PATCH V4 APPLIED ===" -ForegroundColor Green
Write-Host "Now run:"
Write-Host "  flutter clean"
Write-Host "  flutter pub get"
Write-Host "  flutter test"
Write-Host "  flutter run -d windows"
